services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-webhook
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
    ports:
      - "8080:8080"
